apiVersion: v1
kind: Service
metadata:
  labels:
    app: ref-kafka-app-consumer-service-clusterip
  name: ref-kafka-app-consumer-service-clusterip
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: ref-kafka-app-consumer-deployment
  type: ClusterIP
status:
  loadBalancer: {}
